version: '3.5'
services:
  php8.2:
    build: .
    container_name: ngo-management-app
    volumes:
      - "./:/var/www/html"
    ports:
      - "8070:80"
    environment:
      APP_NAME: ngo_management_app
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: demo
      DB_USERNAME: demo
      DB_PASSWORD: demo
      DB_WRITE_HOST: database
      DB_READ_HOST: database
      APP_KEY: 2IUrOF5hkF8W5lAmeucyrUJuK9KBNBc7

  database:
    image: mysql:8
    container_name: ngo-management-mysql
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo 

  phpmyadmin:
    image: phpmyadmin
    container_name: ngo-management-phpmyadmin
    restart: always
    ports:
      - 9878:80
    links:
      - database
    environment:
      PMA_HOST: database 
      PMA_PORT: 3306
      UPLOAD_LIMIT: 3000M

  redis:
    image: redis:latest
    container_name: ngo-management-redis
    ports:
      - "6379:6379"

volumes:
  db-data: {}